config/routes.rb
BasicAuthentication::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions

  match '/admin', to: 'static_pages#admin', as: 'admin'

  root to: 'static_pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :email, :password, :password_confirmation

  EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i

#  validates_uniqueness_of :email
#  validates_format_of :email, with: EMAIL_REGEX
#  validates_length_of :password, minimum: 8

  validates :email,    uniqueness: true,
                           format: { with: EMAIL_REGEX }
  validates :password,     length: { minimum: 8 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to login_url, alert: 'Not Authorized' if current_user.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :authorize, only: :admin
  def home
  end

  def admin
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      # If you want to automatically log the new user into the site:
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BasicAuthentication</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
    <div id="user_header">
      <% if current_user %>
        Logged in as <%= current_user.email %>.
        <%= link_to 'Log Out', logout_path %>
      <% else %>
        <%= link_to 'Sign Up', signup_path %> or
        <%= link_to 'Log In', login_path %>
      <% end %>
    </div>

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>

    <%= yield %>

  </div>
</body>
</html>

app/views/static_pages/admin.html.erb
<h1>StaticPages#admin</h1>
<p>Find me in app/views/static_pages/admin.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>